In [1]:
import wave
import numpy as np

from functions import prepare_audio,snipAI


In [2]:
# snipAI = tf.saved_model.load(pathlib.Path("SnipAI"))
obj = wave.open(str('left/00b01445_nohash_0.wav'), 'rb')
n_samples=obj.getnframes()
signal_wv = obj.readframes(n_samples)
signal_arr = np.frombuffer(signal_wv, dtype=np.int16)
obj.close()

print(signal_arr.shape)

(16000,)


In [3]:
snipAI(prepare_audio(signal_arr))

{'class_ids': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1], dtype=int64)>,
 'predictions': <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-5.419623,  7.936255]], dtype=float32)>,
 'class_names': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'left'], dtype=object)>}